const images = {
  sunny: require('../assets/img/sunny.png'),
  cloudy: require('../assets/img/cloudy.jpg'),
  rainy: require('../assets/img/rainy.jpg'),
  night: require('../assets/img/night.png'),
  Athlone: require('../assets/img/citys/Athlone.jpg'),
  Belmullet: require('../assets/img/citys/Belmullet.jpg'),
  Carlow: require('../assets/img/citys/Carlow.jpg'),
  Carrickmacross: require('../assets/img/citys/Carrickmacross.jpg'),
  Cork: require('../assets/img/citys/Cork.jpg'),
  Drogheda: require('../assets/img/citys/Drogheda.png'),
  Dublin: require('../assets/img/citys/Dublin.jpg'),
  Tramore: require('../assets/img/citys/Dundalk.jpg'),
  Ennis: require('../assets/img/citys/Ennis.jpg'),
  Galway: require('../assets/img/citys/Galway.jpg'),
  Kilkenny: require('../assets/img/citys/KilKenny.jpg'),
  Letterkenny: require('../assets/img/citys/LetterKenny.jpg'),
  Limerick: require('../assets/img/citys/Limerick.jpg'),
  Longford: require('../assets/img/citys/Longford.jpg'),
  Mullingar: require('../assets/img/citys/Mullingar.jpg'),
  Navan: require('../assets/img/citys/Navan.jpg'),
  Sligo: require('../assets/img/citys/Sligo.jpg'),
  Skibbereen: require('../assets/img/citys/Skibbereen.jpg'),
  Tralee: require('../assets/img/citys/Tralee.jpg'),
  Tullamore: require('../assets/img/citys/Tullamore.jpg'),
  Waterville: require('../assets/img/citys/Waterville.jpg'),
  Westport: require('../assets/img/citys/Westport.jpg'),
  hoodies: require('../assets/img/clothes/hoodies.png'),
  hoodies_w: require('../assets/img/clothes/hoodies_w.png'),
  dress: require('../assets/img/clothes/dress.png'),
  shirt: require('../assets/img/clothes/shirt.png'),
  jacket: require('../assets/img/clothes/jacket.png'),
  jacket_w: require('../assets/img/clothes/jacket_w.png'),
  coat: require('../assets/img/clothes/coat.png'),
  coat_w: require('../assets/img/clothes/coat_w.png'),
  long_trouseres: require('../assets/img/trouses/long.png'),
  long_trouseres_w: require('../assets/img/trouses/long_w.png'),
  short_trouseres: require('../assets/img/trouses/short.png'),
  jeans: require('../assets/img/trouses/jeans.png'),
  skirt: require('../assets/img/trouses/skirt.png')
}

export default images